TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devAFG3XXX.db
DATA += devAFG3XXX.proto

#=======================================
include $(TOP)/configure/RULES
