TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += devAFG3XXX.db
# FIXME -- HOW TO INSTALL AFG3XXX.proto????

#=======================================
include $(TOP)/configure/RULES
