TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devAFG3XXXheader.db # common records
DB += devAFG3XXXchannel.db # channel specific

DATA += devAFG3XXX.proto

#=======================================
include $(TOP)/configure/RULES
